#example config file
server:
  host: "0.0.0.0"
  port: 7777

routes:
  - path: "/bin/*"
    target: "https://httpbin.org/"
    description: "Echo Server"

middlewares:
  - name: "LoggingMiddleware"
    enabled: true

  - name: "RateLimitMiddleware"
    enabled: true
    requests_per_minute: 5
