#example config file
server:
  host: "0.0.0.0"
  port: 7777

redis:
  enabled: true  # or false for InMemory Cache
  url: "redis://localhost:6379" 

routes:
  - path: "/bin/*"
    target: "https://httpbin.org/"
    description: "Echo Server"

  - path: "/joke/*"
    target: "https://v2.jokeapi.dev/joke/Any"
    description: "Random Joke"

middlewares:
  - name: "LoggingMiddleware"
    enabled: true

  - name: "RateLimitMiddleware"
    enabled: true
    requests_per_minute: 5

cors:
  allow_origins:
    - "myfront.com"
    - "testreact.space"
    
